data_source: https://raw.githubusercontent.com/g-shreekant/Heart-Disease-Prediction-using-Machine-Learning/master/heart.csv

artifacts: 
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv

  split_data_dir: split_data_dir
  train: train.csv
  test: test.csv

  model_dir: model_dir
  model_filename: ElasticNet.model

  reports_dir: reports_dir
  scores: scores.json 